// src/components/shell/Button.tsx
/**
 * Button – minimal conversion for ShellPageHeader (primary/secondary, pageHeader, md).
 */

import type { ReactNode, AnchorHTMLAttributes, ButtonHTMLAttributes } from 'react';
import { Icon } from './Icon';

export interface ButtonConfig {
  text: string;
  icon?: string;
  href?: string;
  onClick?: () => void;
}

export type ButtonVariant = 'primary' | 'secondary' | 'tertiary' | 'outline' | 'ghost' | 'destructive' | 'dela' | 'dela-pill';
export type ButtonSize = 'xs' | 'sm' | 'md' | 'lg';

export interface ButtonProps {
  variant?: ButtonVariant;
  buttonType?: 'theme' | 'pageHeader';
  size?: ButtonSize;
  icon?: string;
  iconPosition?: 'left' | 'right';
  href?: string;
  className?: string;
  children?: ReactNode;
  onClick?: () => void;
}

export function Button({
  variant = 'primary',
  buttonType = 'theme',
  size = 'md',
  icon,
  iconPosition = 'left',
  href,
  className = '',
  children,
  onClick,
}: ButtonProps) {
  const hasContent = Boolean(children);
  const isIconOnly = Boolean(icon && !hasContent);
  const isDelaVariant = variant === 'dela' || variant === 'dela-pill';
  const classes = [
    'btn',
    `btn--${variant}`,
    buttonType === 'pageHeader' && !isDelaVariant && 'btn--page-header',
    isIconOnly ? `btn--icon-${size}` : `btn--${size}`,
    className,
  ]
    .filter(Boolean)
    .join(' ');
  const content = (
    <>
      {isDelaVariant && <img src="/Stars.svg" alt="" className="btn__dela-stars" />}
      {icon && iconPosition === 'left' && <Icon name={icon} size={size === 'lg' ? 'md' : size === 'md' ? 'sm' : size} />}
      {children}
      {icon && iconPosition === 'right' && <Icon name={icon} size={size === 'lg' ? 'md' : size === 'md' ? 'sm' : size} />}
    </>
  );
  const common = { className: classes, onClick };
  if (href) {
    return <a href={href} {...common as AnchorHTMLAttributes<HTMLAnchorElement>}>{content}</a>;
  }
  return <button type="button" {...common as ButtonHTMLAttributes<HTMLButtonElement>}>{content}</button>;
}

// .cursor/skills/harmony-converter/reference/vue/components/Button/Button.vue
<script setup lang="ts">
import { computed, useSlots } from 'vue'
import ButtonIcons from './ButtonIcons.vue'
import SpinnerIcon from './SpinnerIcon.vue'

export type ButtonVariant =
  | 'primary'
  | 'secondary'
  | 'tertiary'
  | 'outline'
  | 'ghost'
  | 'destructive'
  | 'dela'
  | 'dela-pill'
export type ButtonSize = 'xs' | 'sm' | 'md' | 'lg'
export type ButtonType = 'theme' | 'pageHeader'

const props = withDefaults(
  defineProps<{
    variant?: ButtonVariant
    buttonType?: ButtonType
    size?: ButtonSize
    orientation?: 'horizontal' | 'vertical'
    disabled?: boolean
    loading?: boolean
    loadingText?: string
    icon?: string
    iconPosition?: 'left' | 'right'
    type?: 'button' | 'submit' | 'reset'
    fullWidth?: boolean
    href?: string
    ariaLabel?: string
  }>(),
  {
    variant: 'primary',
    buttonType: 'theme',
    size: 'md',
    orientation: 'horizontal',
    disabled: false,
    loading: false,
    iconPosition: 'left',
    type: 'button',
    fullWidth: false,
  }
)

const emit = defineEmits<{ click: [] }>()

const hasContent = computed(() => !!useSlots().default?.())
const isIconOnly = computed(() => !!props.icon && !hasContent.value && !props.loading)
const isDelaVariant = computed(() => props.variant === 'dela' || props.variant === 'dela-pill')

const buttonClasses = computed(() =>
  [
    'btn',
    `btn--${props.variant}`,
    props.buttonType === 'pageHeader' && !isDelaVariant.value && 'btn--page-header',
    isIconOnly.value ? `btn--icon-${props.size}` : `btn--${props.size}`,
    props.orientation === 'vertical' && 'btn--vertical',
    (props.disabled || props.loading) && 'btn--disabled',
    props.loading && 'btn--loading',
    props.fullWidth && 'btn--full',
  ]
    .filter(Boolean)
    .join(' ')
)

function handleClick(e: Event) {
  if (props.href) e.preventDefault()
  emit('click')
}
</script>

<template>
  <a
    v-if="href"
    :href="href"
    :class="buttonClasses"
    :aria-busy="loading || undefined"
    :aria-label="ariaLabel"
    @click="handleClick"
  >
    <template v-if="loading">
      <SpinnerIcon />
      <span v-if="loadingText">{{ loadingText }}</span>
    </template>
    <template v-else>
      <img v-if="isDelaVariant" src="/Stars.svg" alt="" class="btn__dela-stars" />
      <ButtonIcons v-if="icon && iconPosition === 'left'" :name="icon" />
      <slot />
      <ButtonIcons v-if="icon && iconPosition === 'right'" :name="icon" />
    </template>
  </a>
  <button
    v-else
    :type="type"
    :class="buttonClasses"
    :disabled="disabled || loading"
    :aria-busy="loading || undefined"
    :aria-label="ariaLabel"
    @click="emit('click')"
  >
    <template v-if="loading">
      <SpinnerIcon />
      <span v-if="loadingText">{{ loadingText }}</span>
    </template>
    <template v-else>
      <img v-if="isDelaVariant" src="/Stars.svg" alt="" class="btn__dela-stars" />
      <ButtonIcons v-if="icon && iconPosition === 'left'" :name="icon" />
      <slot />
      <ButtonIcons v-if="icon && iconPosition === 'right'" :name="icon" />
    </template>
  </button>
</template>
