// .cursor/skills/harmony-converter/reference/vue/components/Button/Button.vue
<script setup lang="ts">
import { computed, useSlots } from 'vue'
import ButtonIcons from './ButtonIcons.vue'
import SpinnerIcon from './SpinnerIcon.vue'

export type ButtonVariant =
  | 'primary'
  | 'secondary'
  | 'tertiary'
  | 'outline'
  | 'ghost'
  | 'destructive'
  | 'dela'
  | 'dela-pill'
export type ButtonSize = 'xs' | 'sm' | 'md' | 'lg'
export type ButtonType = 'theme' | 'pageHeader'

const props = withDefaults(
  defineProps<{
    variant?: ButtonVariant
    buttonType?: ButtonType
    size?: ButtonSize
    orientation?: 'horizontal' | 'vertical'
    disabled?: boolean
    loading?: boolean
    loadingText?: string
    icon?: string
    iconPosition?: 'left' | 'right'
    type?: 'button' | 'submit' | 'reset'
    fullWidth?: boolean
    href?: string
    ariaLabel?: string
  }>(),
  {
    variant: 'primary',
    buttonType: 'theme',
    size: 'md',
    orientation: 'horizontal',
    disabled: false,
    loading: false,
    iconPosition: 'left',
    type: 'button',
    fullWidth: false,
  }
)

const emit = defineEmits<{ click: [] }>()

const hasContent = computed(() => !!useSlots().default?.())
const isIconOnly = computed(() => !!props.icon && !hasContent.value && !props.loading)
const isDelaVariant = computed(() => props.variant === 'dela' || props.variant === 'dela-pill')

const buttonClasses = computed(() =>
  [
    'btn',
    `btn--${props.variant}`,
    props.buttonType === 'pageHeader' && !isDelaVariant.value && 'btn--page-header',
    isIconOnly.value ? `btn--icon-${props.size}` : `btn--${props.size}`,
    props.orientation === 'vertical' && 'btn--vertical',
    (props.disabled || props.loading) && 'btn--disabled',
    props.loading && 'btn--loading',
    props.fullWidth && 'btn--full',
  ]
    .filter(Boolean)
    .join(' ')
)

function handleClick(e: Event) {
  if (props.href) e.preventDefault()
  emit('click')
}
</script>

<template>
  <a
    v-if="href"
    :href="href"
    :class="buttonClasses"
    :aria-busy="loading || undefined"
    :aria-label="ariaLabel"
    @click="handleClick"
  >
    <template v-if="loading">
      <SpinnerIcon />
      <span v-if="loadingText">{{ loadingText }}</span>
    </template>
    <template v-else>
      <img v-if="isDelaVariant" src="/Stars.svg" alt="" class="btn__dela-stars" />
      <ButtonIcons v-if="icon && iconPosition === 'left'" :name="icon" />
      <slot />
      <ButtonIcons v-if="icon && iconPosition === 'right'" :name="icon" />
    </template>
  </a>
  <button
    v-else
    :type="type"
    :class="buttonClasses"
    :disabled="disabled || loading"
    :aria-busy="loading || undefined"
    :aria-label="ariaLabel"
    @click="emit('click')"
  >
    <template v-if="loading">
      <SpinnerIcon />
      <span v-if="loadingText">{{ loadingText }}</span>
    </template>
    <template v-else>
      <img v-if="isDelaVariant" src="/Stars.svg" alt="" class="btn__dela-stars" />
      <ButtonIcons v-if="icon && iconPosition === 'left'" :name="icon" />
      <slot />
      <ButtonIcons v-if="icon && iconPosition === 'right'" :name="icon" />
    </template>
  </button>
</template>

// .cursor/skills/harmony-converter/reference/angular/components/button/button.ts
import { Component, input, output } from '@angular/core';
import { CommonModule } from '@angular/common';

export type ButtonVariant =
  | 'primary'
  | 'secondary'
  | 'tertiary'
  | 'outline'
  | 'ghost'
  | 'destructive'
  | 'dela'
  | 'dela-pill';
export type ButtonSize = 'xs' | 'sm' | 'md' | 'lg';
export type ButtonType = 'theme' | 'pageHeader';

@Component({
  selector: 'app-button',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './button.html',
  host: {
    '[class.app-button--full]': 'fullWidth()',
  },
})
export class Button {
  variant = input<ButtonVariant>('primary');
  buttonType = input<ButtonType>('theme');
  size = input<ButtonSize>('md');
  orientation = input<'horizontal' | 'vertical'>('horizontal');
  disabled = input<boolean>(false);
  loading = input<boolean>(false);
  loadingText = input<string>();
  icon = input<string>();
  iconPosition = input<'left' | 'right'>('left');
  type = input<'button' | 'submit' | 'reset'>('button');
  fullWidth = input<boolean>(false);
  href = input<string>();
  ariaLabel = input<string>();
  isIconOnly = input<boolean>(false);

  click = output<void>();

  get _isIconOnly(): boolean {
    return this.isIconOnly();
  }

  get isDelaVariant(): boolean {
    const v = this.variant();
    return v === 'dela' || v === 'dela-pill';
  }

  get buttonClasses(): string {
    const variant = this.variant();
    const buttonType = this.buttonType();
    const size = this.size();
    const isIconOnly = this._isIconOnly;
    const isDelaVariant = this.isDelaVariant;
    const disabled = this.disabled();
    const loading = this.loading();
    const orientation = this.orientation();
    const fullWidth = this.fullWidth();
    return [
      'btn',
      `btn--${variant}`,
      buttonType === 'pageHeader' && !isDelaVariant && 'btn--page-header',
      isIconOnly ? `btn--icon-${size}` : `btn--${size}`,
      orientation === 'vertical' && 'btn--vertical',
      (disabled || loading) && 'btn--disabled',
      loading && 'btn--loading',
      fullWidth && 'btn--full',
    ]
      .filter(Boolean)
      .join(' ');
  }

  handleClick(e: Event): void {
    (e as MouseEvent).preventDefault();
    if (this.disabled() || this.loading()) return;
    this.click.emit();
  }
}
